frase=str(input('Digite uma frase :\n')).upper().strip()
print('Analisando a frase : \n{}'.format(''.join(frase)))
print('Possui {} vezes a letra A '.format(frase.count('A')))
print('A letra A aparece na posição : {}'.format(frase.find('A')+1))
print('A última letra A aparece na posição : {}'.format(frase.rfind('A')+1))
